### ISSUE TITLE
Make it possible to uncheck specific bookmarks from scan results

### ISSUE THREAD

**Issue by 35609902357** [MrOtherGuy/bookmark-batch-updater#3]
The panel is so narrow it makes impossible to see the output, so I can see `https://inputurl.com/example_parameters => https://outputurl.co` because the panel is over and long urls are always cut. The panel should resize automatically so the output can be clearly visible, or it should expand as the size of the window as soon as it is opened (overkill, but a possible workaround)

**Comment by MrOtherGuy** [comment]
This might not be doable because Firefox imposes restrictions on panel width. But, it might be doable to open the controls UI in a new tab instead of a popup panel - come to think of it, that's probably more suitable UI in the first place since the tool isn't something that you'll want to use all the time.

**Comment by 35609902357** [comment]
Having this extension running in its own tab would be great! There's no need at all for the panel, having its own tab would mean more space and might also solve #2, because the panel closes whenever you click outside, but the tab must be explicitly closed

**Comment by MrOtherGuy** [comment]
I can work o this sometime next week probably.

**Comment by MrOtherGuy** [comment]
I was able to do a quick test on a tab-based UI. Actually, it's very easy since I could just load the popup-UI in a tab instead.

But I'm throwing some questions here if you (or someone else) have some input.

* Is in-tab UI fit for all purposes or does it need an option to select which one is used?
* What more information should the in-tab UI show if any? Popup doesn't show much because space is pretty limited.
* Controls could perhaps be improved with in-tab UI. How?

**Comment by 35609902357** [comment]
1. - This extension is for batch editing bookmarks, I can't think of a single scenario where it would be needed as a panel in order to stay on the tab, especially since the panel cannot be closed or else #2
2. - It may diaplay url input & output of all matching links, making it scrollable from left to right would be very useful in case of long links
   - A quick explanation for RegExp formatting would be useful too (see #1)
3. - `RegExp` is comprehensive of the other options, `http-to-https` is limited because not websites still support https, so the bookmarks need to be handpicked. Downgrading https to http, if/when useful (think .onion addresses for example), is only possible in `RegExp`, and changing domain does not allow to switch protocol either to http or https, so perhaps leaving only RegExp and implementing wildcards (see #1) might be beneficial. This would unleash all the power of the [Redirector](https://addons.mozilla.org/en-US/android/addon/redirector/) extension but for bookmarks managing and would crown this extension as the only true bookmark manager for Firefox

**Comment by MrOtherGuy** [comment]
Yeah, I too think that havingte popup as an ootion doesn

**Comment by MrOtherGuy** [comment]
Don't click close issue by accident kids.

Anyhow, I have to agree that having the popup as an option doesn't seem to bring any value. So I'll probably move fully to tab based UI.

But I'm not so sure if listing all the bookmarks with their corresponding result makes sense. Because there could be thousands of similar results especially with http-to-https.

It could be worth it perhaps if I'm going to add a way to furtger filter the list after scanning by making it possible to "uncheck" individual scan results. But that's a topic for future improvements.

Http-to-https and domain matching indeed don't do anything that regexp couldn't do, but they exist for convenience only. And I believe that if one is looking for such batch editing functionality then chances are very good that it is for one of those reasons.

I also agree that showing a brief example or guide when regexp is selected might be a good idea.

**Comment by 35609902357** [comment]
> But I'm not so sure if listing all the bookmarks with their corresponding result makes sense. Because there could be thousands of similar results especially with http-to-https.

Empty space is not needed anyway, so having all the output on the right instead of empty space cannot make anything worse, but an undesired output might be discovered before the trigger is pulled, it's easier to mistake if you have to do it in your mind. I'm thinking this in the context of #1, as wildcards and regexp would open the door for more mistake possibilities.

> It could be worth it perhaps if I'm going to add a way to furtger filter the list after scanning by making it possible to "uncheck" individual scan results.

That was one feature I wanted to ask, I refrained from opening an issue because I didn't want you to feel burdened and I was planning to wait until the other issues were closed, but that's absolutely worth it, because not all domains in one's bookmarks necessarily switched to https for example, or many other possibilities in the case of domains and many more in the case of wildcards/RegExp (although carefully planning the wildcards might make this unnecessary, it would be a great added value in terms of simplicity and ease of use)

**Comment by MrOtherGuy** [comment]
The latest version of the extension opens the UI in a new tab. So I'm re-purposing this issue to uncheck specific scan results

**Comment by MrOtherGuy** [comment]
This should be fixed by cf1d1a593919f87df9108ed4ea32519f0e1b556b

It will be available when I release v1.0

**Comment by 07416** [comment]
> This should be fixed by [cf1d1a5](https://github.com/MrOtherGuy/bookmark-batch-updater/commit/cf1d1a593919f87df9108ed4ea32519f0e1b556b)
> 
> It will be available when I release v1.0

The issue can be closed.
